# $Id: Makefile 6691 2009-03-23 07:43:49Z rurban $
#
# themes/Crao/Makefile
#
# minify CSS and JS
#

CSS_SRC = crao.css
CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))
MAIN    = sticky
JS_MAIN = sticky.js

all	: css js

include ../Makefile.global
