# $Id: Makefile 6691 2009-03-23 07:43:49Z rurban $
#
# themes/blog/Makefile
#
# minify CSS and JS
#

CSS_SRC = Kubrick.css IEFixes.css
#MAIN    = blog
#JS_MAIN = blog.js
JS_REST = 

CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
