# $Id: Makefile 6691 2009-03-23 07:43:49Z rurban $
#
# themes/Wordpress/Makefile
#
# minify CSS and JS
#

CSS_SRC = Wordpress.css
CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
