#!/bin/sh
# TODO: need to check write perms to the .testbox/* (mixed web/cli perms)

chmod -R a+rw .testbox .dumphtml
if [ -d .testbox/page_data -a ! -w .testbox/page_data/AllPages ]; then
  rm -rf .testbox/*
fi
for db in file dba SQL ADODB; do
    php -Cq -d register_argc_argv=1 test.php debug=1 level=10 db=$db | tee all_$db.result
done
