#!/usr/bin/php
<?php
if (count($argv) != 2) {
    echo "usage: $argv[0] pagename\n";
    exit;
}

try {
    $client = new SoapClient("http://phpwiki.nmu.alcatel.fr/phpwiki/PhpWiki.wsdl");
} catch (SoapFault $fault) {
    die($fault->faultstring);
}

$phpwiki = getenv("HOME")."/.phpwiki";
if (!file_exists($phpwiki)) {
    $login = readline("Login: ");
    $password = readline("Password: ");
    $credentials = base64_encode($login.':'.$password);
    if ($fp = fopen($phpwiki, 'w')) {
        fprintf($fp, "%s:%s", $login, $password);
        fclose($fp);
        chmod($phpwiki, 0600);
    }
} else {
    $credentials = base64_encode(file_get_contents($phpwiki));
}

try {
    echo $client->getCurrentRevision($argv[1], $credentials);
    echo "\n";
} catch (SoapFault $e) {
    echo 'Error: ' .  $e->getMessage() . "\n";
}
