# $Id: Makefile 6691 2009-03-23 07:43:49Z rurban $
#
# themes/gforge/Makefile
#
# minify CSS and JS
#

CSS_SRC = gforge.css gforge-print.css gforge-autonumbering.css gforge-rereading.css gforge-fullscreen.css
JS_REST = 

CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
