# $Id$
#
# themes/gforge/Makefile
#
# minify CSS and JS
#

CSS_SRC = gforge.css gforge-print.css gforge-autonumbering.css gforge-rereading.css gforge-fullscreen.css
JS_REST = 

CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
