# $Id: Makefile 6691 2009-03-23 07:43:49Z rurban $
#
# themes/Sidebar/Makefile
#
# minify CSS and JS
#

CSS_SRC = sidebar.css    
#MAIN    = sidebar
#JS_MAIN = sidebar.js
JS_REST = 

CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
