# $Id: Makefile 6691 2009-03-23 07:43:49Z rurban $
#
# themes/SpaceWiki/Makefile
#
# minify CSS and JS
#

CSS_SRC = SpaceWiki.css SpaceWiki-gravimetric.css
CSS_FILES = $(patsubst %.css,%-min.css,$(CSS_SRC))

all	: css

include ../Makefile.global
